service: my-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  lambda_handler:
    handler: my_lambda_function.lambda_handler
    events:
      - http:
          path: /{proxy+}
          method: any

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: product-inventory
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

